import { useContext } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import SingleItem from "@/components/SingleItem";
import { globalContext } from "@/context/appContext";
import { BiSearchAlt } from "react-icons/bi";
import { useForm } from "react-hook-form";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import { GetStaticProps } from "next";
// import axios from "axios";

// type MyData = {
// 	id: number;
// 	title: string;
// 	price: string;
// 	description: string;
// 	image: string;
// };

// export const getStaticProps: GetStaticProps = async () => {
// 	const response = axios.get("https://fakestoreapi.com/products");
// 	const data = (await response).data as MyData[];

// 	return {
// 		props: {
// 			data,
// 		},
// 	};
// };

// interface IProducts {
// 	data: MyData[];
// }

const Home = () => {
	type Inputs = {
		search: string;
	};

	const { products, addItemToCart, productCounts } = useContext(globalContext);
	const { register, handleSubmit } = useForm<Inputs>();

	const customHandleSubmit = (data: Inputs) => {
		if (data.search.length > 3) {
		} else {
			return;
		}
	};

	return (
		<>
			<Head>
				<title>{`Let's shop`}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<Header title="Let's shop!" />
				<div className={styles.search}>
					<label htmlFor="search">Search Item</label>
					<form
						onSubmit={handleSubmit(customHandleSubmit)}
						className={styles.input}
					>
						<input
							{...register("search")}
							type="text"
							autoComplete="off"
							id="search"
							name="search"
							placeholder="Men's clothing, jewelery,electronics..."
						/>
						<button
							type="submit"
							style={{
								cursor: "pointer",
								border: "none",
								outline: "none",
								background: "transparent",
							}}
						>
							<BiSearchAlt size={25} />
						</button>
					</form>
				</div>
				<div className={styles.mainLayout}>
					{products.map((data) => (
						<SingleItem
							productCounts={productCounts}
							addItemToCart={addItemToCart}
							key={data.image + Math.random()}
							product={data}
						/>
					))}
				</div>
			</div>
			<Footer />
		</>
	);
};

export default Home;
